config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tickets
  resource :search, only: [:show, :create]

  namespace :admin do
    resources :railway_stations do
      patch :update_position_order, on: :member
      patch :update_time, on: :member
    end

    resources :trains do
      resources :carriages, shallow: true
    end

    resources :routes
    resources :tickets
    resources :start
  end

  root 'searches#show'
  get  'searches/index'
  get 'admin/start'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/route.rb
class Route < ApplicationRecord
  validates :title, presence: true
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes
  has_many :trains



  validate :stations_count
  before_validation :set_name

  private

  def set_name
    self.title = "#{railway_stations.first.title} - #{railway_stations.last.title}"
  end

  def stations_count
    if railway_stations.size < 2
      errors.add(:base, "Маршрут должн содержать как минимум 2 станции")
    end
  end

end

app/controllers/admin/routes_controller.rb
class Admin::RoutesController < Admin::BaseController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.all
  end

  def show
  end

  def new
    @route = Route.new
  end

  def create
    @route = Route.new(route_params)

    if @route.save
      redirect_to admin_routes_path(@route)
    else
      render :new
    end

  end

  def edit
  end

  def update
    if @route.update(route_params)
      redirect_to admin_routes_path(@route)
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to admin_routes_path
  end

  private

  def route_params
    params.require(:route).permit(:title, railway_station_ids: [])
  end

  def set_route
    @route = Route.find(params[:id])
  end

end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/admin/routes/_form.html.erb
<%= form_for [:admin, @route] do |f| %>
  <%= render 'common/errors', resource: @route %>

    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="field">
      <%= f.label :railway_station_ids %>
      <%= f.collection_select :railway_station_ids, RailwayStation.all, :id, :title, {}, { multiple: true, class: 'form-control' } %>
    </div>

    <div class="actions">

      <%= f.submit t('.submit', action: @route.new_record? ? 'Добавить' : 'Редактировать' ), class: 'btn btn-success', type: "button"  %>
    </div>
<% end %>

app/views/admin/routes/_route_stations.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <td>Название</td>
      <td>Позиция</td>
      <td>Время прибытия</td>
      <td>Время отправления</td>

    </tr>
  </thead>
  <tbody>
  <% @route.railway_stations.ordered.each do |station| %>
      <tr>
        <td><%= station.title %></td>
        <td>
          <%= form_tag update_position_order_admin_railway_station_path(station), method: :patch do %>
            <%= number_field_tag :position, station.position_in(@route) %>
            <%= hidden_field_tag :route_id, @route.id %>
            <%= submit_tag 'Изменить', class: 'btn btn-success', type: "button" %>
          <% end %>
        </td>

        <%= form_tag update_time_admin_railway_station_path(station), method: :patch do %>
            <td><%= time_field_tag :arrival_time, station.up_time(@route, :arrival_time) %></td>
            <td><%= time_field_tag :departure_time, station.up_time(@route, :departure_time) %></td>
            <%= hidden_field_tag :route_id, @route.id %>
            <td> <%= submit_tag 'Изменить', class: 'btn btn-success', type: "button" %></td>
        <% end %>



      </tr>
  <% end %>
  </tbody>



</table>

app/views/admin/routes/_route_trains.html.erb
<ul>
  <% @route.trains.each do |train| %>
      <li><%= train.number %> </li>
  <% end %>
</ul>

app/views/admin/routes/edit.html.erb
<h1>Редактировать маршрут</h1>

<%= render 'form', route: @route %>


<%= link_to 'Назад', admin_railway_stations_path, class: 'btn btn-success', type: "button" %>

app/views/admin/routes/index.html.erb
<h1>Список маршрутов</h1>

<table class="table table-striped" >
  <thead>
  <tr>
    <th>Маршрут</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @routes.each do |route| %>
      <tr>
        <td><%= route.title %></td>
        <td><%= link_to 'Показать', [:admin, route], class: 'btn btn-success', type: "button" %></td>
        <td><%= link_to 'Редактировать', edit_admin_route_path(route), class: 'btn btn-success', type: "button" %></td>
        <td><%= link_to 'Удалить', [:admin, route], method: :delete, data: { confirm: 'Точно удалить?'}, class: 'btn btn-danger', type: "button"  %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Добавить новый маршрут', new_admin_route_path, class: 'btn btn-success', type: "button" %>

app/views/admin/routes/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', route: @route %>


<%= link_to 'Назад', admin_routes_path, class: 'btn btn-success', type: "button" %>

app/views/admin/routes/show.html.erb
<p>
  <strong>Путь:</strong>
  <%= @route.title %>
</p>

<p>
  <strong>Станции в маршруте:</strong>
</p>

<p>
  <% if @route.railway_stations.empty? %>
      На данном маршруте сейчас нет станций. Вы можете <%= link_to 'Добавить', edit_admin_route_path(@route) %>  их.
  <% else %>
      <%= render 'route_stations' %>
  <%end %>
</p>


<p>
  <strong>Поезда на маршруте:</strong>
</p>
<p>
  <% if @route.trains.empty? %>
      Поездов на маршруте нет
  <% else %>
      <%= render 'route_trains' %>
<%end %>
</p>


<%= link_to 'Редактировать', edit_admin_route_path(@route), class: 'btn btn-success', type: "button" %>
<%= link_to 'Назад', admin_routes_path, class: 'btn btn-success', type: "button" %>