config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tickets
  resource :search, only: [:show, :create]

  namespace :admin do
    resources :railway_stations do
      patch :update_position_order, on: :member
      patch :update_time, on: :member
    end

    resources :trains do
      resources :carriages, shallow: true
    end

    resources :routes
    resources :tickets
    resources :start
  end

  root 'searches#show'
  get  'searches/index'
  get 'admin/start'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ticket.rb
class Ticket < ApplicationRecord

  belongs_to :user
  belongs_to :train
  belongs_to :start_station, class_name: "RailwayStation", foreign_key: :start_station_id
  belongs_to :end_station, class_name: "RailwayStation", foreign_key: :end_station_id

  # before_validation :set_user

  private

  def set_user
    user = User.where(name: passenger_name).first

    if @user
      self.user = user
    else
      self.user = User.create(name: passenger_name)
    end
  end

end

app/controllers/admin/tickets_controller.rb
class Admin::TicketsController < Admin::BaseController
  before_action :set_ticket, only: [:show, :destroy, :update, :edit]

  def index
    @tickets = Ticket.all
  end

  def new
    @ticket = Ticket.new(train_id: params[:train_id], start_station_id: params[:start_station_id], end_station_id: params[:end_station_id], user_id: params[:user_id])
  end

  def show
  end

  def create
    @ticket = current_user.tickets.new(ticket_params)

    if @ticket.save
      @ticket = current_user.tickets.new(ticket_params)
      redirect_to @ticket
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @ticket.update(ticket_params)
      redirect_to admin_ticket_path(@ticket)
    else
      render :new
    end
  end

  def destroy
    @ticket.destroy
    redirect_to tickets_path
  end

  private

  def ticket_params
    params.require(:ticket).permit(:train_id, :start_station_id, :end_station_id, :passenger_name, :passenger_number, :user_id)
  end

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
   before_action :authenticate_user!
   before_action :set_ticket, only: [:show, :destroy]


   def index
     @tickets = current_user.tickets
   end

   def new
     @ticket = Ticket.new(train_id: params[:train_id], start_station_id: params[:start_station_id], end_station_id: params[:end_station_id])
   end

   def show
   end

   def create
     @ticket = current_user.tickets.new(ticket_params)

       if @ticket.save
          redirect_to @ticket
       else
          render :new
       end
   end

   def destroy
     @ticket.destroy
     redirect_to tickets_path
   end

   private

   def ticket_params
     params.require(:ticket).permit(:train_id, :start_station_id, :end_station_id, :passenger_name, :passenger_number)
   end

   def set_ticket
     @ticket = current_user.tickets.find(params[:id])
   end
end

app/views/admin/tickets/_form.html.erb
<%= form_for [:admin, @ticket] do |f| %>
        <%= render 'common/errors', resource: @ticket %>

        <div class="field">
        <%= f.label :start_station_id, 'Станция отправления' %>
        <%= f.collection_select :start_station_id, RailwayStation.all, :id, :title,{}, {:class => 'form-control'} %>
      </div>

        <div class="field">
        <%= f.label :end_station_id, 'Станция прибытия' %>
        <%= f.collection_select :end_station_id, RailwayStation.all, :id, :title,{}, {:class => 'form-control'} %>
      </div>

        <div class="field">
        <%= f.label :passenger_name, 'ФИО' %>
        <%= f.text_field :passenger_name, class:'form-control' %>
      </div>

        <div class="field">
        <%= f.label :passenger_number, 'Данные паспорта' %>
        <%= f.text_field :passenger_number, class:'form-control' %>
      </div>

        <div class="field">
        <%= f.label :train_id, 'Поезд' %>
        <%= f.collection_select :train_id, Train.all, :id, :number,{}, {:class => 'form-control'} %>
      </div>

        <div class="field">
        <%= f.label :user_id, 'Пользователь' %>
        <%= f.collection_select :user_id, User.all, :id, :email, {}, {:class => 'form-control'} %>
      </div>

        <div class="actions">
        <%= f.submit "#{@ticket.new_record? ? 'Купить' : 'Изменить'}", class: 'btn btn-success', type: "button" %>
      </div>

    <% end %>

app/views/admin/tickets/_tickets.html.erb
<tr>
  <td><%= tickets.train.number %></td>
  <td><%= tickets.start_station.title %></td>
  <td><%= tickets.end_station.title %></td>
  <td><%= tickets.passenger_name %><td>
  <td><%= tickets.passenger_number %></td>

  <td><%= link_to 'Просмотреть', [:admin, tickets], class: 'btn btn-success', type: "button" %></td>
  <td><%= link_to 'Редактировать', edit_admin_ticket_path(tickets), class: 'btn btn-success', type: "button" %></td>
  <td><%= link_to 'Удалить билет', [:admin, tickets], method: :delete, data: { confirm: 'Вы точно хотите удалить билет?' }, class: 'btn btn-danger', type: "button" %></td>
</tr>

app/views/admin/tickets/edit.html.erb
<h1>Редактирование билета</h1>
 <%=render 'form', ticket: @ticket %>

<p><%= link_to 'Список билетов', admin_tickets_path, class: 'btn btn-success', type: "button" %>  </p>

app/views/admin/tickets/index.html.erb
<h1>Список билетов</h1>

<table class="table table-striped">
  <thead>
  <th>№ поезда</th>
  <th>Станция отпрв.</th>
  <th>Станция назн.</th>
  <th>ФИО</th>
  <th>Паспорт</th>
  </thead>
  <tbody>
    <%= render partial: 'tickets', collection: @tickets %>
  </tbody>
  </table>

<%= link_to 'Купить билет', new_admin_ticket_path, class: 'btn btn-success', type: "button" %>

app/views/admin/tickets/new.html.erb
<h1>Купить билет</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Назад', search_path, class: 'btn btn-success' %>

app/views/admin/tickets/show.html.erb
<p>
  <strong>Номер поезда:</strong>
  <%= @ticket.train.number %>
</p>

<p>
  <strong>Начальная станция:</strong>
  <%= @ticket.start_station.title %>
</p>

<p>
  <strong>Конечная станция:</strong>
  <%= @ticket.end_station.title %>
</p>

<p>
  <strong>Имя пассажира:</strong>
  <%= @ticket.passenger_name %>
</p>

<p>
  <strong>Паспорт:</strong>
  <%= @ticket.passenger_number %>
</p>

<p>
  <strong>Email пользователя:</strong>
  <%= @ticket.user.email %>
</p>

<%= link_to 'Список билетов', admin_tickets_path, class: 'btn btn-success', type: "button" %>