config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tickets
  resource :search, only: [:show, :create]

  namespace :admin do
    resources :railway_stations do
      patch :update_position_order, on: :member
      patch :update_time, on: :member
    end

    resources :trains do
      resources :carriages, shallow: true
    end

    resources :routes
    resources :tickets
    resources :start
  end

  root 'searches#show'
  get  'searches/index'
  get 'admin/start'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/carriage.rb
class Carriage < ApplicationRecord
  validates :number, uniqueness: { scope: :train_id }
  belongs_to :train

  before_validation :set_number, on: :create

  TYPES = {
      econom: 'EconomCarriage',
      coupe: 'CoupeCarriage',
      sitting: 'SedentaryCarriage',
      sv: 'SvCarriage'
  }

  TYPES.each do |key, value|
    scope key.to_sym, -> { where(type: value) }
  end

  # scope :EconomCarriage, -> {where(type: 'Плацкарт')}
  # scope :CoupeCarriage, -> {where(type: 'Купе')}
  # scope :SedentaryCarriage, -> {where(type: 'Сидячий')}
  # scope :SvCarriage, -> {where(type: 'СВ')}

  scope :ordered, ->(order) { order(number: order ? 'asc' : 'desc') }

  private

  def set_number
    self.number = (train.carriages.maximum('number') || 0).next
  end

end

app/controllers/admin/carriages_controller.rb
class Admin::CarriagesController < Admin::BaseController
  before_action :set_carriage, only: [:show, :edit, :update, :destroy]
  before_action :set_train, only: [:new, :create]

  def index
    @carriages = Carriage.all
  end

  def show
    @carriage = Carriage.find(params[:id])
  end

  def new
    @carriage = Carriage.new
  end

  def create
    @carriage = @train.carriages.new(carriage_params)

      if @carriage.save
        redirect_to  admin_trains_path(@train)
      else
        render :new
      end

    end

    def edit
    end

    def update
    if @carriage.update(carriage_params)
      redirect_to admin_train_carriages_path(@carriage)
    else
      render :edit
    end
  end

  def destroy
    @carriage.destroy
    redirect_to admin_train_carriages_path(@carriage)
  end

  private

  def carriage_params
    params.require(:carriage).permit(:type, :number_seat_place, :number_top_place, :number_bottom_place, :number_side_bottom_place, :number_side_top_place, :train_id)
  end

  def set_carriage
    @carriage = Carriage.find(params[:id])
  end

  def set_train
    @train = Train.find(params[:train_id])
  end

end

app/views/admin/carriages/_carriage.html.erb
<tr>
  <td><%= carriage.id %></td>
  <td><%= carriage.number %></td>
  <td>
    <% if carriage.type.eql?('CoupeCarriage') %>
        <%= "Купе" %>
    <% elsif carriage.type.eql?('EconomCarriage') %>
        <%= "Плацкарт" %>
    <% elsif carriage.type.eql?('SedentaryCarriage') %>
        <%= "Сидячий" %>
    <% elsif carriage.type.eql?('SvCarriage') %>
        <%= "СВ" %>
    <% end %>
  </td>
  <td><%= link_to 'Показать', admin_carriage_path(carriage), class: "btn btn-success" %></td>
  <td><%= link_to 'Редактировать', edit_admin_carriage_path(carriage), class: "btn btn-success" %></td>
  <td><%= link_to 'Удалить', admin_carriage_path(carriage), method: :delete, data: { confirm: 'Точно удалить?' }, class:"btn btn-danger" %></td>
</tr>

app/views/admin/carriages/_coupe_carriage.html.erb
<% if @carriage.coupe? %>
    <p>
      <strong>Количество нижних мест:</strong>
      <%= @carriage.number_bottom_place %></br>
      <strong>Количество верхних мест:</strong>
      <%= @carriage.number_top_place %>
    </p>
<% end %>

app/views/admin/carriages/_econom_carriage.html.erb
<% if @carriage.econom? %>
    <p>
      <strong>Количество нижних мест:</strong>
      <%= @carriage.number_bottom_place %></br>
      <strong>Количество верхних мест:</strong>
      <%= @carriage.number_top_place %></br>
      <strong>Количество нижних боковых мест:</strong>
      <%= @carriage.number_side_bottom_place %></br>
      <strong>Количество верхних боковых мест:</strong>
      <%= @carriage.number_side_top_place %>
    </p>
<% end %>

app/views/admin/carriages/_form.html.erb
<%= form_for [:admin, @train, carriage.becomes(Carriage)] do |f| %>
  <%= render 'common/errors', resource: @carriage %>

     <div class="field">
      <%= f.label 'Тип вагона' %><br>
      <%= f.select :type, Carriage::TYPES.values,{}, {:class => 'form-control'} %>
        </div>


    <div class="field">
      <%= f.label 'Количество верхних мест' %><br>
      <%= f.number_field :number_top_place, class: "form-control" %>
    </div>

    <div class="field">
      <%= f.label 'Количество нижних мест' %><br>
      <%= f.number_field :number_bottom_place, class: "form-control" %>
    </div>


    <div class="field">
      <%= f.label 'Количество верхних боковых мест' %><br>
      <%= f.number_field :number_side_top_place, class: "form-control" %>
    </div>

    <div class="field">
      <%= f.label 'Количество нижних боковых мест' %><br>
      <%= f.number_field :number_side_bottom_place, class: "form-control" %>
    </div>

    <div class="field">
      <%= f.label 'Количество сидячих мест' %><br>
      <%= f.number_field :number_seat_place, class: "form-control" %>
    </div>


    <div class="field">
      <%= f.label :train, "Номер поезда" %>
      <%= f.collection_select :train_id, Train.all, :id, :number,{}, {:class => 'form-control'} %>
    </div>


    <div class="actions">
      <%= f.submit "#{@carriage.new_record? ? 'Создать вагон' : 'Изменить вагон'}", class: 'btn btn-success', type: "button"  %>
    </div>
<% end %>

app/views/admin/carriages/_sedentary_carriage.html.erb
<% if @carriage.sedentary? %>
    <p>
      <strong>Количество сидячих мест:</strong>
      <%= @carriage.number_seat_place %>
    </p>
<% end %>

app/views/admin/carriages/_sv_carriage.html.erb
<% if @carriage.sv? %>
    <p>
      <strong>Количество нижних мест:</strong>
      <%= @carriage.number_bottom_place %></br>
    </p>
<% end %>

app/views/admin/carriages/edit.html.erb
<h1>Редактировать вагон</h1>

<%= render 'form', carriage: @carriage %>


<%= link_to 'Назад', admin_carriage_path, class: 'btn btn-success', type: "button" %>

app/views/admin/carriages/index.html.erb
<h1>Список вагонов</h1>

<table class="table table-striped">
  <thead>
  <tr>
    <th>ID вагона</th>
    <th>Номер вагона</th>
    <th >Тип вагона</th>
  </tr>
  </thead>

  <tbody>
  <%= render partial: "carriage", collection: @carriages %>
  </tbody>
</table>

<br>

<%= link_to 'Добавить новый вагон', new_admin_train_carriage_path, class: 'btn btn-success', type: "button" %>

app/views/admin/carriages/new.html.erb
<h1>Добавить вагон</h1>

<%= render 'form', carriage: @carriage %>


<%= link_to 'Назад', admin_train_carriages_path, class: 'btn btn-success', type: "button" %>

app/views/admin/carriages/show.html.erb
<p>
  <strong>Номер вагона:</strong>
  <%= @carriage.number %>
</p>

<p>
<strong>Тип вагона:</strong>
  <% if @carriage.type.eql?('CoupeCarriage') %>
      <%= 'Купе' %>
  <% elsif @carriage.type.eql?('EconomCarriage') %>
      <%= 'Плацкарт' %>
  <% elsif @carriage.type.eql?('SedentaryCarriage') %>
      <%= 'Сидячий' %>
  <% elsif @carriage.type.eql?('SvCarriage') %>
      <%= 'СВ' %>
  <% end %>
</p>

<p>
  <strong>ID Поезда:</strong>
  <%= @carriage.train_id %>
</p>

<%= render @carriage.type.underscore, carriage: @carriage %>



<p>
  <% if @carriage.train.nil? %>
      Вагон еще не прицеплен
  <% else %>
      Вагон прицеплен к поезду номер: <%= @carriage.train.number %></p>
  <%end %>
  </p>



<%= link_to 'Редактировать', edit_admin_carriage_path(@carriage), class: 'btn btn-success', type: "button" %> |
<%= link_to 'Назад', admin_train_carriages_path(@carriage.train), class: 'btn btn-success', type: "button" %>