config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tickets
  resource :search, only: [:show, :create]

  namespace :admin do
    resources :railway_stations do
      patch :update_position_order, on: :member
      patch :update_time, on: :member
    end

    resources :trains do
      resources :carriages, shallow: true
    end

    resources :routes
    resources :tickets
    resources :start
  end

  root 'searches#show'
  get  'searches/index'
  get 'admin/start'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/train.rb
class Train < ApplicationRecord
  validates :number, presence: true
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
  belongs_to :route
  has_many :tickets
  has_many :carriages

  before_create :set_number

  private

  def set_number
    self.number = Train.count.next
  end

  def count_place(type, place)
    carriages.where(type: type).sum(place)
  end

end

app/controllers/admin/trains_controller.rb
class Admin::TrainsController < Admin::BaseController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  # GET /trains
  # GET /trains.json
  def index
    @trains = Train.all
  end

  # GET /trains/1
  # GET /trains/1.json
  def show
  end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit
  end

  # POST /trains
  # POST /trains.json
  def create
    @train = Train.new(train_params)


      if @train.save
        redirect_to admin_trains_path(@train)
      else
         render :new
      end
  end

  # PATCH/PUT /trains/1
  # PATCH/PUT /trains/1.json
  def update

      if @train.update(train_params)
        redirect_to admin_trains_path(@train)
      else
        render :edit
      end

  end

  # DELETE /trains/1
  # DELETE /trains/1.json
  def destroy
    @train.destroy
    redirect_to admin_trains_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def train_params
      params.require(:train).permit(:number, :current_station_id, :sorting_carriage, :route_id)
    end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/admin/trains/_carriages.html.erb
<ul>
  <% @train.carriages.ordered(@train.sorting_carriage).each do |carriage| %>
      <li>
        <%= link_to "Вагон № #{carriage.number}", admin_carriage_path(carriage) %>
      </li>
  <% end %>
</ul>

app/views/admin/trains/_form.html.erb
<%= form_for [:admin, @train] do |f| %>
    <%= render 'common/errors', resource: @train %>

  <div class="field">
    <%= f.label :number %>
    <%= f.number_field :number, class: 'form-control' %>
  </div>

    <div class="field">
      <%= f.label :current_station %>
      <%= f.collection_select :current_station_id, RailwayStation.all, :id, :title,{}, {:class => 'form-control'} %>
    </div>

    <div class="field">
      <%= f.label :route %>
      <%= f.collection_select :route_id, Route.all, :id, :title,{}, {:class => 'form-control'} %>
    </div>

    <div class="field">
      <%= f.label :sorting_carriage, 'Нумерация с головы состава' %>
      <%= f.check_box :sorting_carriage, {checked: true}, type:"checkbox"  %>
    </div>


  <div class="actions">
    <%= f.submit "#{@train.new_record? ? 'Добавить поезд' : 'Редактировать поезд'}", class: 'btn btn-success', type: "button" %>
  </div>
<% end %>

app/views/admin/trains/_train.html.erb
<tr>
  <td><%= train.number %></td>
  <td><%= link_to 'Show', [:admin, train], class: 'btn btn-success', type: "button" %></td>
  <td><%= link_to 'Edit', edit_admin_train_path(train), class: 'btn btn-success', type: "button" %></td>
  <td><%= link_to 'Destroy', [:admin, train], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger', type: "button" %></td>
</tr>

app/views/admin/trains/edit.html.erb
<h1>Редактировать поезд</h1>

<%= render 'form', train: @train %>

<%= link_to 'Посмотреть', @train %> |
<%= link_to 'Назад', trains_path %>

app/views/admin/trains/index.html.erb
<h1>Список поездов</h1>

<table>
  <thead>
    <tr>
      <th>Номер поезда</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <%= render @trains %>

  </tbody>
</table>

<br>

<%= link_to 'Добаить новый поезд', new_admin_train_path, class: 'btn btn-success', type: "button"  %>

app/views/admin/trains/new.html.erb
<h1>Новый поезд</h1>

<%= render 'form', train: @train %>

<%= link_to 'Назад', admin_trains_path, class: 'btn btn-success', type: "button" %>

app/views/admin/trains/show.html.erb
<div class="col-lg-3">
<p class="bg-info">
  <strong>Номер поезда:</strong>
</p>
  <p>
  <%= @train.number %>
</p>
</div>
<div class="col-lg-3">
<p class="bg-info">
  <strong>На станции</strong>
</p>
<p>
  <% if @train.current_station.present? %>
    <%= @train.current_station.title %>
  <% else %>
    Не указано
  <%end %>
</p>
</div>
<div class="col-lg-3">

  <p class="bg-info"><strong >Маршрут</strong></p>
  <p>
  <% if @train.route.present? %>
      <%= @train.route.title %>
  <% else %>
      Маршрут еще не назначен
  <%end %>
</p>
</div>
<div class="col-lg-3">
<p class="bg-info">
  <strong>Номера вагонов</strong>
</p>
  <p>
  <% if @train.carriages.empty? %>
    У поезда нет вагонов
  <% else %>
      <%= render 'carriages' %>
  <% end %>
</p>
</div>
<div class="col-lg-12">
<%= link_to 'Добавить вагон', new_admin_train_carriage_path(@train),class: 'btn btn-success', type: "button"  %>
<%= link_to 'Редактировать', edit_admin_train_path(@train), class: 'btn btn-success', type: "button"  %>
<%= link_to 'Назад', admin_trains_path, class: 'btn btn-success', type: "button"  %>
</div>